# Section 1: Getting Started With Pandas

We will begin by introducing the `Series`, `DataFrame`, and `Index` classes, which are the basic building blocks of the pandas library, and showing how to work with them. By the end of this section, you will be able to create DataFrames and perform operations on them to inspect and filter the data.

## Table of Contents
1. [Pandas Series](#Pandas-Series)
2. [Anatomy of a DataFrame](#Anatomy-of-a-DataFrame)
3. [Creating DataFrames](#Creating-Dataframes)
4. [Calculating summary statistics](#Calculating-summary-statistics)

In [2]:
import pandas as pd

## 1. Pandas Series 
- A Pandas Series is a one-dimensional array of indexed data. The Pandas Series wraps both a sequence of values and a sequence of indices.
- The Pandas Series has an explicitly defined index associated with the values. The index can be integers or values of any desired type. 
- We can access the values and index attributes.

In [3]:
#Pandas series can be created from a list or array as follows.
data = pd.Series([0.25, 0.5, 0.75, 1.0])
print(data)
print(type(data))

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64
<class 'pandas.core.series.Series'>

In [3]:
# Data can also be accessed by the associated index
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [4]:
# Data can also be accessed by via the familiar Python square-bracket notation.
data[3]

1.0

In [5]:
data[:]

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [4]:
data.index

RangeIndex(start=0, stop=4, step=1)

In [5]:
# The index can be integers or values of any desired type.
# use strings as an index: 
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=['a', 'b', 'c', 'd'])
print(data)
data['a']

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

np.float64(0.25)

In [8]:
data['a']

0.25

### 1.2. Pandas Series formats 
- Pandas series as a list of array - just discussed before 
- Pandas series as a specialized dictionary:  
A dictionary is a structure that maps arbitrary keys to a set of arbitrary values, and a Series is a structure that maps typed keys to a set of typed values.  It is more efficient than a Python list for certain operations, the type information of a Pandas Series makes it much more efficient than Python dictionaries for certain operations.

In [6]:
# NYC tree species percentage dictionary
NYC_treespecies_dict = { 'London Planetree': 13.3,
               'HoneyLocust': 9.9,
               'Callery Pear': 9.0,
               'Pin Oak':8.2,
               'Norway Maple': 5.2,
}
print(NYC_treespecies_dict)
NYC_treespecies = pd.Series(NYC_treespecies_dict)
NYC_treespecies

{'London Planetree': 13.3, 'HoneyLocust': 9.9, 'Callery Pear': 9.0, 'Pin Oak': 8.2, 'Norway Maple': 5.2}

London Planetree    13.3
HoneyLocust          9.9
Callery Pear         9.0
Pin Oak              8.2
Norway Maple         5.2
dtype: float64

In [7]:
NYC_treespecies.index

Index(['London Planetree', 'HoneyLocust', 'Callery Pear', 'Pin Oak',
       'Norway Maple'],
      dtype='object')

In [56]:
NYC_treespecies.values

array([13.3,  9.9,  9. ,  8.2,  5.2])

In [10]:
# print % of HoneyLocust
NYC_treespecies['HoneyLocust']
NYC_treespecies['HoneyLocust':'Pin Oak']

HoneyLocust     9.9
Callery Pear    9.0
Pin Oak         8.2
dtype: float64

In [10]:
# print % of HoneyLocust using Dict, line 2 will not work
NYC_treespecies_dict['HoneyLocust']
#NYC_treespecies_dict['HoneyLocust':'Pin Oak']

9.9

### 1.3. Constructing a pandas series object
- ``` pd.Series(data, index=index)```
- where index is an optional argument, and data can be one of many entities.
- Data can be a list or a scalar. Data can be a dictionary, in which index defaults to the sorted dictionary keys

In [14]:
# Creat a pandas series as a list of array 
pd.Series([2,4,6])

0    2
1    4
2    6
dtype: int64

In [15]:
# Create a pandas data as a scalar 
a = pd.Series(5, index=['a','b','c'])
print(a)

a    5
b    5
c    5
dtype: int64

In [17]:
# Creat a pandas data as  a dictionary 
# NYC tree species percentage dictionary
NYC_treespecies_dict = { 'London Planetree': 13.3,
               'HoneyLocust': 9.9,
               'Callery Pear': 9.0,
               'Pin Oak':8.2,
               'Norway Maple': 5.2,
}
NYC_treespecies = pd.Series(NYC_treespecies_dict)
print(NYC_treespecies)

NYC_treespecies = pd.Series(NYC_treespecies_dict, index = ['HoneyLocust', 'Norway Maple'])
print(NYC_treespecies)

London Planetree    13.3
HoneyLocust          9.9
Callery Pear         9.0
Pin Oak              8.2
Norway Maple         5.2
dtype: float64
HoneyLocust     9.9
Norway Maple    5.2
dtype: float64

### 1.4. Data Indexing and Selection
#### Series as dictionary - Like a dictionary, the Series object provides a mapping from a collection of keys to a collection of values:

In [20]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [21]:
data['b']

0.5

In [22]:
# We can also use dictionary-like Python expressions and methods to examine the keys/indices and values:
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [23]:
list(data.items())

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

In [24]:
# You can assign a new index value
data['b'] = 2
data

a    0.25
b    2.00
c    0.75
d    1.00
dtype: float64

#### Series as one-dimensional array

In [25]:
# slicing by explicit index
data['a':'c']

a    0.25
b    2.00
c    0.75
dtype: float64

In [26]:
# slicing by implicit integer index
data[0:2]

a    0.25
b    2.00
dtype: float64

In [11]:
# masking
print(data)
data[(data > 0.3) & (data < 0.8)]

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

b    0.50
c    0.75
dtype: float64

In [12]:
# fancy indexing
data[['a', 'd']]

a    0.25
d    1.00
dtype: float64

#### Indexers: loc and iloc
 loc gets DataFrame rows & columns by labels/names and iloc gets by integer Index/position. For loc, if the label is not present it gives a key error. For iloc, if the position is not present it gives an index error.

In [13]:
data = pd.Series(['a', 'b', 'c'])
data

0    a
1    b
2    c
dtype: object

In [58]:
data[1]

'b'

In [60]:
# the loc attribute allows indexing and slicing that always references the explicit index:
data.loc[0:2]

0    a
1    b
2    c
dtype: object

In [ ]:
# The iloc attribute allows indexing and slicing that always references the implicit Python-style index:

In [61]:
data.iloc[0:2]

0    a
1    b
dtype: object

In [14]:
data[0:2]

0    a
1    b
dtype: object

## Anatomy-of-a-DataFrame

A **DataFrame** is composed of one or more **Series**. The names of the **Series** form the column names, and the row labels form the **Index**.

[Pandsa can read and write different formats csvm  of files](https://pandas.pydata.org/pandas-docs/version/1.1.3/getting_started/intro_tutorials/02_read_write.html#min-tut-02-read-write) - csv, json,xls, hdf5,sql etc. We read csv files for this excercise.

In [16]:
# Read NYC tree data. I downloaded the tree data, which can be read directly from the links below.
# https://data.cityofnewyork.us/Environment/2015-Street-Tree-Census-Tree-Data/uvpi-gqnh/about_data.
# Download the 2015 tree data and put it under the /data subdirectory in your current working directory. 
# Read 2015 tree census data using pd.read_csv 
tree2015 = pd.read_csv('data/2015_Street_Tree_Census.csv', nrows=5)
tree2015

,tree_id,block_id,created_at,tree_dbh,stump_diam,curb_loc,status,health,spc_latin,spc_common,...,boro_ct,state,latitude,longitude,x_sp,y_sp,council district,census tract,bin,bbl
0,180683,348711,08/27/2015,3,0,OnCurb,Alive,Fair,Acer rubrum,red maple,...,4073900,New York,40.723092,-73.844215,1027431.148,202756.7687,29,739,4052307,4022210001
1,200540,315986,09/03/2015,21,0,OnCurb,Alive,Fair,Quercus palustris,pin oak,...,4097300,New York,40.794111,-73.818679,1034455.701,228644.8374,19,973,4101931,4044750045
2,204026,218365,09/05/2015,3,0,OnCurb,Alive,Good,Gleditsia triacanthos var. inermis,honeylocust,...,3044900,New York,40.717581,-73.936608,1001822.831,200716.8913,34,449,3338310,3028870001
3,204337,217969,09/05/2015,10,0,OnCurb,Alive,Good,Gleditsia triacanthos var. inermis,honeylocust,...,3044900,New York,40.713537,-73.934456,1002420.358,199244.2531,34,449,3338342,3029250001
4,189565,223043,08/30/2015,21,0,OnCurb,Alive,Good,Tilia americana,American linden,...,3016500,New York,40.666778,-73.975979,990913.775,182202.4260,39,165,3025654,3010850052

#### Series:

In [7]:
tree2015.tree_id

0    180683
1    200540
2    204026
3    204337
4    189565
Name: tree_id, dtype: int64

#### Columns:

In [8]:
tree2015.columns

Index(['tree_id', 'block_id', 'created_at', 'tree_dbh', 'stump_diam',
       'curb_loc', 'status', 'health', 'spc_latin', 'spc_common', 'steward',
       'guards', 'sidewalk', 'user_type', 'problems', 'root_stone',
       'root_grate', 'root_other', 'trunk_wire', 'trnk_light', 'trnk_other',
       'brch_light', 'brch_shoe', 'brch_other', 'address', 'postcode',
       'zip_city', 'community board', 'borocode', 'borough', 'cncldist',
       'st_assem', 'st_senate', 'nta', 'nta_name', 'boro_ct', 'state',
       'latitude', 'longitude', 'x_sp', 'y_sp', 'council district',
       'census tract', 'bin', 'bbl'],
      dtype='object')

#### Index:

In [9]:
tree2015.index

RangeIndex(start=0, stop=5, step=1)

## Creating DataFrames

We can create DataFrames from a variety of sources such as other Python objects, flat files, webscraping, and API requests. Here, we will see just a couple of examples, but be sure to check out [this page](https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html) in the documentation for a complete list.

### Using a flat file

In [18]:
tree2015 = pd.read_csv('data/2015_Street_Tree_Census.csv')

*Tip: There are many parameters to this function to handle some initial processing while reading in the file &ndash; be sure check out the [documentation](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html).*

In [17]:
pd.read_csv?

Signature:
pd.read_csv(
    filepath_or_buffer: 'FilePath | ReadCsvBuffer[bytes] | ReadCsvBuffer[str]',
    *,
    sep: 'str | None | lib.NoDefault' = <no_default>,
    delimiter: 'str | None | lib.NoDefault' = None,
    header: "int | Sequence[int] | None | Literal['infer']" = 'infer',
    names: 'Sequence[Hashable] | None | lib.NoDefault' = <no_default>,
    index_col: 'IndexLabel | Literal[False] | None' = None,
    usecols: 'UsecolsArgType' = None,
    dtype: 'DtypeArg | None' = None,
    engine: 'CSVEngine | None' = None,
    converters: 'Mapping[Hashable, Callable] | None' = None,
    true_values: 'list | None' = None,
    false_values: 'list | None' = None,
    skipinitialspace: 'bool' = False,
    skiprows: 'list[int] | int | Callable[[Hashable], bool] | None' = None,
    skipfooter: 'int' = 0,
    nrows: 'int | None' = None,
    na_values: 'Hashable | Iterable[Hashable] | Mapping[Hashable, Iterable[Hashable]] | None' = None,
    keep_default_na: 'bool' = True,
    na_filter: 'bool' = True,
    verbose: 'bool | lib.NoDefault' = <no_default>,
    skip_blank_lines: 'bool' = True,
    parse_dates: 'bool | Sequence[Hashable] | None' = None,
    infer_datetime_format: 'bool | lib.NoDefault' = <no_default>,
    keep_date_col: 'bool | lib.NoDefault' = <no_default>,
    date_parser: 'Callable | lib.NoDefault' = <no_default>,
    date_format: 'str | dict[Hashable, str] | None' = None,
    dayfirst: 'bool' = False,
    cache_dates: 'bool' = True,
    iterator: 'bool' = False,
    chunksize: 'int | None' = None,
    compression: 'CompressionOptions' = 'infer',
    thousands: 'str | None' = None,
    decimal: 'str' = '.',
    lineterminator: 'str | None' = None,
    quotechar: 'str' = '"',
    quoting: 'int' = 0,
    doublequote: 'bool' = True,
    escapechar: 'str | None' = None,
    comment: 'str | None' = None,
    encoding: 'str | None' = None,
    encoding_errors: 'str | None' = 'strict',
    dialect: 'str | csv.Dialect | None' = None,
    on_bad_lines: 'str' = 'error',
    delim_whitespace: 'bool | lib.NoDefault' = <no_default>,
    low_memory: 'bool' = True,
    memory_map: 'bool' = False,
    float_precision: "Literal['high', 'legacy'] | None" = None,
    storage_options: 'StorageOptions | None' = None,
    dtype_backend: 'DtypeBackend | lib.NoDefault' = <no_default>,
) -> 'DataFrame | TextFileReader'
Docstring:
Read a comma-separated values (csv) file into DataFrame.

Also supports optionally iterating or breaking of the file
into chunks.

Additional help can be found in the online docs for
`IO Tools <https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html>`_.

Parameters
----------
filepath_or_buffer : str, path object or file-like object
    Any valid string path is acceptable. The string could be a URL. Valid
    URL schemes include http, ftp, s3, gs, and file. For file URLs, a host is
    expected. A local file could be: file://localhost/path/to/table.csv.

    If you want to pass in a path object, pandas accepts any ``os.PathLike``.

    By file-like object, we refer to objects with a ``read()`` method, such as
    a file handle (e.g. via builtin ``open`` function) or ``StringIO``.
sep : str, default ','
    Character or regex pattern to treat as the delimiter. If ``sep=None``, the
    C engine cannot automatically detect
    the separator, but the Python parsing engine can, meaning the latter will
    be used and automatically detect the separator from only the first valid
    row of the file by Python's builtin sniffer tool, ``csv.Sniffer``.
    In addition, separators longer than 1 character and different from
    ``'\s+'`` will be interpreted as regular expressions and will also force
    the use of the Python parsing engine. Note that regex delimiters are prone
    to ignoring quoted data. Regex example: ``'\r\t'``.
delimiter : str, optional
    Alias for ``sep``.
header : int, Sequence of int, 'infer' or None, default 'infer'
    Row number(s) containing column labels and marking the start of the
    data (zero-indexed). Default behavior is to infer the column names: if no ``names``
    are passed the behavior is identical to ``header=0`` and column
    names are inferred from the first line of the file, if column
    names are passed explicitly to ``names`` then the behavior is identical to
    ``header=None``. Explicitly pass ``header=0`` to be able to
    replace existing names. The header can be a list of integers that
    specify row locations for a :class:`~pandas.MultiIndex` on the columns
    e.g. ``[0, 1, 3]``. Intervening rows that are not specified will be
    skipped (e.g. 2 in this example is skipped). Note that this
    parameter ignores commented lines and empty lines if
    ``skip_blank_lines=True``, so ``header=0`` denotes the first line of
    data rather than the first line of the file.
names : Sequence of Hashable, optional
    Sequence of column labels to apply. If the file contains a header row,
    then you should explicitly pass ``header=0`` to override the column names.
    Duplicates in this list are not allowed.
index_col : Hashable, Sequence of Hashable or False, optional
  Column(s) to use as row label(s), denoted either by column labels or column
  indices.  If a sequence of labels or indices is given, :class:`~pandas.MultiIndex`
  will be formed for the row labels.

  Note: ``index_col=False`` can be used to force pandas to *not* use the first
  column as the index, e.g., when you have a malformed file with delimiters at
  the end of each line.
usecols : Sequence of Hashable or Callable, optional
    Subset of columns to select, denoted either by column labels or column indices.
    If list-like, all elements must either
    be positional (i.e. integer indices into the document columns) or strings
    that correspond to column names provided either by the user in ``names`` or
    inferred from the document header row(s). If ``names`` are given, the document
    header row(s) are not taken into account. For example, a valid list-like
    ``usecols`` parameter would be ``[0, 1, 2]`` or ``['foo', 'bar', 'baz']``.
    Element order is ignored, so ``usecols=[0, 1]`` is the same as ``[1, 0]``.
    To instantiate a :class:`~pandas.DataFrame` from ``data`` with element order
    preserved use ``pd.read_csv(data, usecols=['foo', 'bar'])[['foo', 'bar']]``
    for columns in ``['foo', 'bar']`` order or
    ``pd.read_csv(data, usecols=['foo', 'bar'])[['bar', 'foo']]``
    for ``['bar', 'foo']`` order.

    If callable, the callable function will be evaluated against the column
    names, returning names where the callable function evaluates to ``True``. An
    example of a valid callable argument would be ``lambda x: x.upper() in
    ['AAA', 'BBB', 'DDD']``. Using this parameter results in much faster
    parsing time and lower memory usage.
dtype : dtype or dict of {Hashable : dtype}, optional
    Data type(s) to apply to either the whole dataset or individual columns.
    E.g., ``{'a': np.float64, 'b': np.int32, 'c': 'Int64'}``
    Use ``str`` or ``object`` together with suitable ``na_values`` settings
    to preserve and not interpret ``dtype``.
    If ``converters`` are specified, they will be applied INSTEAD
    of ``dtype`` conversion.

    .. versionadded:: 1.5.0

        Support for ``defaultdict`` was added. Specify a ``defaultdict`` as input where
        the default determines the ``dtype`` of the columns which are not explicitly
        listed.
engine : {'c', 'python', 'pyarrow'}, optional
    Parser engine to use. The C and pyarrow engines are faster, while the python engine
    is currently more feature-complete. Multithreading is currently only supported by
    the pyarrow engine.

    .. versionadded:: 1.4.0

        The 'pyarrow' engine was added as an *experimental* engine, and some features
        are unsupported, or may not work correctly, with this engine.
converters : dict of {Hashable : Callable}, optional
    Functions for converting values in specified columns. Keys can either
    be column labels or column indices.
true_values : list, optional
    Values to consider as ``True`` in addition to case-insensitive variants of 'True'.
false_values : list, optional
    Values to consider as ``False`` in addition to case-insensitive variants of 'False'.
skipinitialspace : bool, default False
    Skip spaces after delimiter.
skiprows : int, list of int or Callable, optional
    Line numbers to skip (0-indexed) or number of lines to skip (``int``)
    at the start of the file.

    If callable, the callable function will be evaluated against the row
    indices, returning ``True`` if the row should be skipped and ``False`` otherwise.
    An example of a valid callable argument would be ``lambda x: x in [0, 2]``.
skipfooter : int, default 0
    Number of lines at bottom of file to skip (Unsupported with ``engine='c'``).
nrows : int, optional
    Number of rows of file to read. Useful for reading pieces of large files.
na_values : Hashable, Iterable of Hashable or dict of {Hashable : Iterable}, optional
    Additional strings to recognize as ``NA``/``NaN``. If ``dict`` passed, specific
    per-column ``NA`` values.  By default the following values are interpreted as
    ``NaN``: " ", "#N/A", "#N/A N/A", "#NA", "-1.#IND", "-1.#QNAN", "-NaN", "-nan",
    "1.#IND", "1.#QNAN", "<NA>", "N/A", "NA", "NULL", "NaN", "None",
    "n/a", "nan", "null ".

keep_default_na : bool, default True
    Whether or not to include the default ``NaN`` values when parsing the data.
    Depending on whether ``na_values`` is passed in, the behavior is as follows:

    * If ``keep_default_na`` is ``True``, and ``na_values`` are specified, ``na_values``
      is appended to the default ``NaN`` values used for parsing.
    * If ``keep_default_na`` is ``True``, and ``na_values`` are not specified, only
      the default ``NaN`` values are used for parsing.
    * If ``keep_default_na`` is ``False``, and ``na_values`` are specified, only
      the ``NaN`` values specified ``na_values`` are used for parsing.
    * If ``keep_default_na`` is ``False``, and ``na_values`` are not specified, no
      strings will be parsed as ``NaN``.

    Note that if ``na_filter`` is passed in as ``False``, the ``keep_default_na`` and
    ``na_values`` parameters will be ignored.
na_filter : bool, default True
    Detect missing value markers (empty strings and the value of ``na_values``). In
    data without any ``NA`` values, passing ``na_filter=False`` can improve the
    performance of reading a large file.
verbose : bool, default False
    Indicate number of ``NA`` values placed in non-numeric columns.

    .. deprecated:: 2.2.0
skip_blank_lines : bool, default True
    If ``True``, skip over blank lines rather than interpreting as ``NaN`` values.
parse_dates : bool, list of Hashable, list of lists or dict of {Hashable : list}, default False
    The behavior is as follows:

    * ``bool``. If ``True`` -> try parsing the index. Note: Automatically set to
      ``True`` if ``date_format`` or ``date_parser`` arguments have been passed.
    * ``list`` of ``int`` or names. e.g. If ``[1, 2, 3]`` -> try parsing columns 1, 2, 3
      each as a separate date column.
    * ``list`` of ``list``. e.g.  If ``[[1, 3]]`` -> combine columns 1 and 3 and parse
      as a single date column. Values are joined with a space before parsing.
    * ``dict``, e.g. ``{'foo' : [1, 3]}`` -> parse columns 1, 3 as date and call
      result 'foo'. Values are joined with a space before parsing.

    If a column or index cannot be represented as an array of ``datetime``,
    say because of an unparsable value or a mixture of timezones, the column
    or index will be returned unaltered as an ``object`` data type. For
    non-standard ``datetime`` parsing, use :func:`~pandas.to_datetime` after
    :func:`~pandas.read_csv`.

    Note: A fast-path exists for iso8601-formatted dates.
infer_datetime_format : bool, default False
    If ``True`` and ``parse_dates`` is enabled, pandas will attempt to infer the
    format of the ``datetime`` strings in the columns, and if it can be inferred,
    switch to a faster method of parsing them. In some cases this can increase
    the parsing speed by 5-10x.

    .. deprecated:: 2.0.0
        A strict version of this argument is now the default, passing it has no effect.

keep_date_col : bool, default False
    If ``True`` and ``parse_dates`` specifies combining multiple columns then
    keep the original columns.
date_parser : Callable, optional
    Function to use for converting a sequence of string columns to an array of
    ``datetime`` instances. The default uses ``dateutil.parser.parser`` to do the
    conversion. pandas will try to call ``date_parser`` in three different ways,
    advancing to the next if an exception occurs: 1) Pass one or more arrays
    (as defined by ``parse_dates``) as arguments; 2) concatenate (row-wise) the
    string values from the columns defined by ``parse_dates`` into a single array
    and pass that; and 3) call ``date_parser`` once for each row using one or
    more strings (corresponding to the columns defined by ``parse_dates``) as
    arguments.

    .. deprecated:: 2.0.0
       Use ``date_format`` instead, or read in as ``object`` and then apply
       :func:`~pandas.to_datetime` as-needed.
date_format : str or dict of column -> format, optional
    Format to use for parsing dates when used in conjunction with ``parse_dates``.
    The strftime to parse time, e.g. :const:`"%d/%m/%Y"`. See
    `strftime documentation
    <https://docs.python.org/3/library/datetime.html
    #strftime-and-strptime-behavior>`_ for more information on choices, though
    note that :const:`"%f"` will parse all the way up to nanoseconds.
    You can also pass:

    - "ISO8601", to parse any `ISO8601 <https://en.wikipedia.org/wiki/ISO_8601>`_
        time string (not necessarily in exactly the same format);
    - "mixed", to infer the format for each element individually. This is risky,
        and you should probably use it along with `dayfirst`.

    .. versionadded:: 2.0.0
dayfirst : bool, default False
    DD/MM format dates, international and European format.
cache_dates : bool, default True
    If ``True``, use a cache of unique, converted dates to apply the ``datetime``
    conversion. May produce significant speed-up when parsing duplicate
    date strings, especially ones with timezone offsets.

iterator : bool, default False
    Return ``TextFileReader`` object for iteration or getting chunks with
    ``get_chunk()``.
chunksize : int, optional
    Number of lines to read from the file per chunk. Passing a value will cause the
    function to return a ``TextFileReader`` object for iteration.
    See the `IO Tools docs
    <https://pandas.pydata.org/pandas-docs/stable/io.html#io-chunking>`_
    for more information on ``iterator`` and ``chunksize``.

compression : str or dict, default 'infer'
    For on-the-fly decompression of on-disk data. If 'infer' and 'filepath_or_buffer' is
    path-like, then detect compression from the following extensions: '.gz',
    '.bz2', '.zip', '.xz', '.zst', '.tar', '.tar.gz', '.tar.xz' or '.tar.bz2'
    (otherwise no compression).
    If using 'zip' or 'tar', the ZIP file must contain only one data file to be read in.
    Set to ``None`` for no decompression.
    Can also be a dict with key ``'method'`` set
    to one of {``'zip'``, ``'gzip'``, ``'bz2'``, ``'zstd'``, ``'xz'``, ``'tar'``} and
    other key-value pairs are forwarded to
    ``zipfile.ZipFile``, ``gzip.GzipFile``,
    ``bz2.BZ2File``, ``zstandard.ZstdDecompressor``, ``lzma.LZMAFile`` or
    ``tarfile.TarFile``, respectively.
    As an example, the following could be passed for Zstandard decompression using a
    custom compression dictionary:
    ``compression={'method': 'zstd', 'dict_data': my_compression_dict}``.

    .. versionadded:: 1.5.0
        Added support for `.tar` files.

    .. versionchanged:: 1.4.0 Zstandard support.

thousands : str (length 1), optional
    Character acting as the thousands separator in numerical values.
decimal : str (length 1), default '.'
    Character to recognize as decimal point (e.g., use ',' for European data).
lineterminator : str (length 1), optional
    Character used to denote a line break. Only valid with C parser.
quotechar : str (length 1), optional
    Character used to denote the start and end of a quoted item. Quoted
    items can include the ``delimiter`` and it will be ignored.
quoting : {0 or csv.QUOTE_MINIMAL, 1 or csv.QUOTE_ALL, 2 or csv.QUOTE_NONNUMERIC, 3 or csv.QUOTE_NONE}, default csv.QUOTE_MINIMAL
    Control field quoting behavior per ``csv.QUOTE_*`` constants. Default is
    ``csv.QUOTE_MINIMAL`` (i.e., 0) which implies that only fields containing special
    characters are quoted (e.g., characters defined in ``quotechar``, ``delimiter``,
    or ``lineterminator``.
doublequote : bool, default True
   When ``quotechar`` is specified and ``quoting`` is not ``QUOTE_NONE``, indicate
   whether or not to interpret two consecutive ``quotechar`` elements INSIDE a
   field as a single ``quotechar`` element.
escapechar : str (length 1), optional
    Character used to escape other characters.
comment : str (length 1), optional
    Character indicating that the remainder of line should not be parsed.
    If found at the beginning
    of a line, the line will be ignored altogether. This parameter must be a
    single character. Like empty lines (as long as ``skip_blank_lines=True``),
    fully commented lines are ignored by the parameter ``header`` but not by
    ``skiprows``. For example, if ``comment='#'``, parsing
    ``#empty\na,b,c\n1,2,3`` with ``header=0`` will result in ``'a,b,c'`` being
    treated as the header.
encoding : str, optional, default 'utf-8'
    Encoding to use for UTF when reading/writing (ex. ``'utf-8'``). `List of Python
    standard encodings
    <https://docs.python.org/3/library/codecs.html#standard-encodings>`_ .

encoding_errors : str, optional, default 'strict'
    How encoding errors are treated. `List of possible values
    <https://docs.python.org/3/library/codecs.html#error-handlers>`_ .

    .. versionadded:: 1.3.0

dialect : str or csv.Dialect, optional
    If provided, this parameter will override values (default or not) for the
    following parameters: ``delimiter``, ``doublequote``, ``escapechar``,
    ``skipinitialspace``, ``quotechar``, and ``quoting``. If it is necessary to
    override values, a ``ParserWarning`` will be issued. See ``csv.Dialect``
    documentation for more details.
on_bad_lines : {'error', 'warn', 'skip'} or Callable, default 'error'
    Specifies what to do upon encountering a bad line (a line with too many fields).
    Allowed values are :

    - ``'error'``, raise an Exception when a bad line is encountered.
    - ``'warn'``, raise a warning when a bad line is encountered and skip that line.
    - ``'skip'``, skip bad lines without raising or warning when they are encountered.

    .. versionadded:: 1.3.0

    .. versionadded:: 1.4.0

        - Callable, function with signature
          ``(bad_line: list[str]) -> list[str] | None`` that will process a single
          bad line. ``bad_line`` is a list of strings split by the ``sep``.
          If the function returns ``None``, the bad line will be ignored.
          If the function returns a new ``list`` of strings with more elements than
          expected, a ``ParserWarning`` will be emitted while dropping extra elements.
          Only supported when ``engine='python'``

    .. versionchanged:: 2.2.0

        - Callable, function with signature
          as described in `pyarrow documentation
          <https://arrow.apache.org/docs/python/generated/pyarrow.csv.ParseOptions.html
          #pyarrow.csv.ParseOptions.invalid_row_handler>`_ when ``engine='pyarrow'``

delim_whitespace : bool, default False
    Specifies whether or not whitespace (e.g. ``' '`` or ``'\t'``) will be

## Inspecting the data
Now that we have some data, we need to perform an initial inspection of it. This gives us information on what the data looks like, how many rows/columns there are, and how much data we have.

Let's inspect the `tree2015` data.

#### How many rows and columns are there?

In [19]:
tree2015.shape

(683788, 45)

#### What are the column names?

In [18]:
tree2015.columns

Index(['tree_id', 'block_id', 'created_at', 'tree_dbh', 'stump_diam',
       'curb_loc', 'status', 'health', 'spc_latin', 'spc_common', 'steward',
       'guards', 'sidewalk', 'user_type', 'problems', 'root_stone',
       'root_grate', 'root_other', 'trunk_wire', 'trnk_light', 'trnk_other',
       'brch_light', 'brch_shoe', 'brch_other', 'address', 'postcode',
       'zip_city', 'community board', 'borocode', 'borough', 'cncldist',
       'st_assem', 'st_senate', 'nta', 'nta_name', 'boro_ct', 'state',
       'latitude', 'longitude', 'x_sp', 'y_sp', 'council district',
       'census tract', 'bin', 'bbl'],
      dtype='object')

#### What type of data does each column currently hold?

In [19]:
tree2015.dtypes

tree_id               int64
block_id              int64
created_at           object
tree_dbh              int64
stump_diam            int64
curb_loc             object
status               object
health               object
spc_latin            object
spc_common           object
steward              object
guards               object
sidewalk             object
user_type            object
problems             object
root_stone           object
root_grate           object
root_other           object
trunk_wire           object
trnk_light           object
trnk_other           object
brch_light           object
brch_shoe            object
brch_other           object
address              object
postcode              int64
zip_city             object
community board       int64
borocode              int64
borough              object
cncldist              int64
st_assem              int64
st_senate             int64
nta                  object
nta_name             object
boro_ct               int64
state                object
latitude            float64
longitude           float64
x_sp                float64
y_sp                float64
council district    float64
census tract        float64
bin                 float64
bbl                 float64
dtype: object

Special note: In pandas: dtype=object means the column holds general Python objects (usually strings, but could be mixed).

#### What does the data look like?

In [20]:
tree2015.head()

,tree_id,block_id,created_at,tree_dbh,stump_diam,curb_loc,status,health,spc_latin,spc_common,...,boro_ct,state,latitude,longitude,x_sp,y_sp,council district,census tract,bin,bbl
0,180683,348711,08/27/2015,3,0,OnCurb,Alive,Fair,Acer rubrum,red maple,...,4073900,New York,40.723092,-73.844215,1027431.148,202756.7687,29.0,739.0,4052307.0,4.022210e+09
1,200540,315986,09/03/2015,21,0,OnCurb,Alive,Fair,Quercus palustris,pin oak,...,4097300,New York,40.794111,-73.818679,1034455.701,228644.8374,19.0,973.0,4101931.0,4.044750e+09
2,204026,218365,09/05/2015,3,0,OnCurb,Alive,Good,Gleditsia triacanthos var. inermis,honeylocust,...,3044900,New York,40.717581,-73.936608,1001822.831,200716.8913,34.0,449.0,3338310.0,3.028870e+09
3,204337,217969,09/05/2015,10,0,OnCurb,Alive,Good,Gleditsia triacanthos var. inermis,honeylocust,...,3044900,New York,40.713537,-73.934456,1002420.358,199244.2531,34.0,449.0,3338342.0,3.029250e+09
4,189565,223043,08/30/2015,21,0,OnCurb,Alive,Good,Tilia americana,American linden,...,3016500,New York,40.666778,-73.975979,990913.775,182202.4260,39.0,165.0,3025654.0,3.010850e+09

Sometimes there may be extraneous data at the end of the file, so checking the bottom few rows is also important:

In [21]:
tree2015.tail()

,tree_id,block_id,created_at,tree_dbh,stump_diam,curb_loc,status,health,spc_latin,spc_common,...,boro_ct,state,latitude,longitude,x_sp,y_sp,council district,census tract,bin,bbl
683783,155433,217978,08/18/2015,25,0,OnCurb,Alive,Good,Quercus palustris,pin oak,...,3051900,New York,40.713211,-73.954944,9.967407e+05,199121.6363,34.0,519.0,3062513.0,3.023690e+09
683784,183795,348185,08/29/2015,7,0,OnCurb,Alive,Good,Cladrastis kentukea,Kentucky yellowwood,...,4070700,New York,40.715194,-73.856650,1.023989e+06,199873.6475,29.0,707.0,4075448.0,4.031810e+09
683785,166161,401670,08/22/2015,12,0,OnCurb,Alive,Good,Acer rubrum,red maple,...,5020100,New York,40.620762,-74.136517,9.463514e+05,165466.0763,50.0,201.0,5011657.0,5.004080e+09
683786,184028,504204,08/29/2015,9,0,OnCurb,Alive,Good,Acer rubrum,red maple,...,2023502,New York,40.850828,-73.903115,1.011054e+06,249271.9507,15.0,23502.0,2007757.0,2.028120e+09
683787,200607,306527,09/03/2015,23,0,OnCurb,Alive,Fair,Acer rubrum,red maple,...,4134100,New York,40.732165,-73.787526,1.043136e+06,206095.5383,24.0,1341.0,4153657.0,4.071360e+09

#### Get some information about the DataFrame

In [22]:
tree2015.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 683788 entries, 0 to 683787
Data columns (total 45 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   tree_id           683788 non-null  int64
 1   block_id          683788 non-null  int64
 2   created_at        683788 non-null  object
 3   tree_dbh          683788 non-null  int64
 4   stump_diam        683788 non-null  int64
 5   curb_loc          683788 non-null  object
 6   status            683788 non-null  object
 7   health            652172 non-null  object
 8   spc_latin         652169 non-null  object
 9   spc_common        652169 non-null  object
 10  steward           164350 non-null  object
 11  guards            79866 non-null   object
 12  sidewalk          652172 non-null  object
 13  user_type         683788 non-null  object
 14  problems          225844 non-null  object
 15  root_stone        683788 non-null  object
 16  root_grate        683788 non-null  object
 17  root_other        683788 non-null  object
 18  trunk_wire        683788 non-null  object
 19  trnk_light        683788 non-null  object
 20  trnk_other        683788 non-null  object
 21  brch_light        683788 non-null  object
 22  brch_shoe         683788 non-null  object
 23  brch_other        683788 non-null  object
 24  address           683788 non-null  object
 25  postcode          683788 non-null  int64
 26  zip_city          683788 non-null  object
 27  community board   683788 non-null  int64
 28  borocode          683788 non-null  int64
 29  borough           683788 non-null  object
 30  cncldist          683788 non-null  int64
 31  st_assem          683788 non-null  int64
 32  st_senate         683788 non-null  int64
 33  nta               683788 non-null  object
 34  nta_name          683788 non-null  object
 35  boro_ct           683788 non-null  int64
 36  state             683788 non-null  object
 37  latitude          683788 non-null  float64
 38  longitude         683788 non-null  float64
 39  x_sp              683788 non-null  float64
 40  y_sp              683788 non-null  float64
 41  council district  677269 non-null  float64
 42  census tract      677269 non-null  float64
 43  bin               674229 non-null  float64
 44  bbl               674229 non-null  float64
dtypes: float64(8), int64(11), object(26)
memory usage: 234.8+ MB

### [Exercise 1.1](./wk5.ipynb#Exercise-1.1)
Download NYC 2005 tree data from this link: https://data.cityofnewyork.us/Environment/2005-Street-Tree-Census/29bw-z7pj/about_data. 
Examine the first 5 rows.

### [Exercise 1.2](./wk5.ipynb#Exercise-1.2)

##### Find the dimensions (number of rows and number of columns) in the data.

## Extracting subsets

A crucial part of working with DataFrames is extracting subsets of the data: finding rows that meet a certain set of criteria, isolating columns/rows of interest, etc. After narrowing down our data, we are closer to discovering insights. This section will be the backbone of many analysis tasks.

#### Selecting columns

We can select columns as attributes if their names would be valid Python variables:

In [28]:
tree2015.tree_id

0         180683
1         200540
2         204026
3         204337
4         189565
           ...
683783    155433
683784    183795
683785    166161
683786    184028
683787    200607
Name: tree_id, Length: 683788, dtype: int64

You can select multiple columns at once this way:

In [20]:
tree2015[['tree_id', 'spc_common']]

        tree_id           spc_common
0        180683            red maple
1        200540              pin oak
2        204026          honeylocust
3        204337          honeylocust
4        189565      American linden
...         ...                  ...
683783   155433              pin oak
683784   183795  Kentucky yellowwood
683785   166161            red maple
683786   184028            red maple
683787   200607            red maple

[683788 rows x 2 columns]

#### Selecting rows

In [21]:
# In pandas, the [] (square bracket) syntax does not accept row and column selectors together like NumPy does.
tree2015[100:104, ['tree_id','spc_common']]

InvalidIndexError: (slice(100, 104, None), ['tree_id', 'spc_common'])

#### Indexing

Instead using `iloc[]` to select rows and columns by their position:

In [22]:
tree2015.iloc[100:104, [0, 3, 4, 6]]

     tree_id  tree_dbh  stump_diam status
100   204203        11           0  Alive
101   203385        23           0  Alive
102   196372        12           0  Alive
103   192889        27           0  Alive

We use `loc[]` to select by name:

In [23]:
tree2015.loc[100:104, 'tree_id':'tree_dbh']

     tree_id  block_id  created_at  tree_dbh
100   204203    415447  09/05/2015        11
101   203385    347979  09/04/2015        23
102   196372    103300  09/02/2015        12
103   192889    210568  08/31/2015        27
104   203760    302373  09/05/2015         2

In [26]:
tree2015.loc[100:104, ['tree_id', 'tree_dbh']]

     tree_id  tree_dbh
100   204203        11
101   203385        23
102   196372        12
103   192889        27
104   203760         2

Please notice the difference between iloc and loc.

#### Filtering with Boolean masks

A **Boolean mask** is a array-like structure of Boolean values &ndash; it's a way to specify which rows/columns we want to select (`True`) and which we don't (`False`).

Here's an example of a Boolean mask for a subset of `red_maple` species with `tree_dbh` > 40 inches

In [27]:
tree2015[(tree2015['tree_dbh'] > 40) & (tree2015.spc_common == 'red maple')]

,tree_id,block_id,created_at,tree_dbh,stump_diam,curb_loc,status,health,spc_latin,spc_common,...,boro_ct,state,latitude,longitude,x_sp,y_sp,council district,census tract,bin,bbl
20379,215697,415159,09/11/2015,51,0,OffsetFromCurb,Alive,Good,Acer rubrum,red maple,...,5013204,New York,40.563976,-74.127037,9.489533e+05,144773.8257,50.0,13204.0,NaN,NaN
37509,245977,334366,09/22/2015,41,0,OnCurb,Alive,Good,Acer rubrum,red maple,...,4056800,New York,40.719414,-73.731788,1.058598e+06,201492.3129,27.0,568.0,4231341.0,4.108110e+09
56702,225461,514975,09/15/2015,41,0,OnCurb,Alive,Good,Acer rubrum,red maple,...,2042800,New York,40.893187,-73.844652,1.027200e+06,264728.0536,12.0,428.0,2069001.0,2.050160e+09
94481,277901,511000,10/02/2015,41,0,OnCurb,Alive,Good,Acer rubrum,red maple,...,2030000,New York,40.853706,-73.828386,1.031725e+06,250351.9682,13.0,300.0,2047760.0,2.042490e+09
231191,430014,402102,11/05/2015,43,0,OnCurb,Alive,Good,Acer rubrum,red maple,...,5002100,New York,40.625125,-74.083394,9.611006e+05,167037.1837,49.0,21.0,5014082.0,5.005420e+09
250198,456594,406164,11/14/2015,42,0,OnCurb,Alive,Good,Acer rubrum,red maple,...,5011202,New York,40.575706,-74.096047,9.575685e+05,149036.2430,50.0,11202.0,5054231.0,5.037340e+09
262847,481551,402603,11/24/2015,50,0,OnCurb,Alive,Good,Acer rubrum,red maple,...,5021300,New York,40.629782,-74.137094,9.461964e+05,168752.5684,49.0,213.0,5024838.0,5.010490e+09
300944,498911,407837,12/06/2015,154,0,OnCurb,Alive,Good,Acer rubrum,red maple,...,5029103,New York,40.600109,-74.166549,9.380000e+05,157956.3377,50.0,29103.0,5035610.0,5.021100e+09
331153,550014,403735,03/09/2016,48,0,OffsetFromCurb,Alive,Good,Acer rubrum,red maple,...,5000900,New York,40.643690,-74.080369,9.619465e+05,173800.1351,49.0,9.0,5000324.0,5.000210e+09
331213,550016,403735,03/09/2016,64,0,OffsetFromCurb,Alive,Good,Acer rubrum,red maple,...,5000900,New York,40.643542,-74.080251,9.619791e+05,173746.2657,49.0,9.0,5131387.0,5.000200e+09
331892,553057,407316,04/06/2016,45,0,OnCurb,Alive,Good,Acer rubrum,red maple,...,5007000,New York,40.595055,-74.073374,9.638728e+05,156079.7023,50.0,70.0,5048185.0,5.032760e+09
340241,550010,403735,03/09/2016,41,0,OnCurb,Alive,Good,Acer rubrum,red maple,...,5000900,New York,40.644138,-74.081016,9.617670e+05,173963.4543,49.0,9.0,5000328.0,5.000210e+09
357880,563090,333465,05/20/2016,43,0,OnCurb,Alive,Good,Acer rubrum,red maple,...,4051600,New York,40.705764,-73.749526,1.053695e+06,196504.5762,27.0,516.0,4234925.0,4.109650e+09
358672,548874,401455,03/01/2016,41,0,OnCurb,Alive,Good,Acer rubrum,red maple,...,5005900,New York,40.618597,-74.103045,9.556428e+05,164664.8827,49.0,59.0,5006684.0,5.002460e+09
373799,587374,330743,06/15/2016,46,0,OnCurb,Alive,Good,Acer rubrum,red maple,...,4066000,New York,40.657189,-73.729599,1.059275e+06,178824.0013,31.0,660.0,4290313.0,4.136630e+09
441770,664936,323516,08/14/2016,45,0,OffsetFromCurb,Alive,Good,Acer rubrum,red maple,...,4109700,New York,40.770063,-73.775231,1.046509e+06,219911.3637,19.0,1097.0,4135826.0,4.061100e+09
621135,137558,405876,08/12/2015,41,0,OnCurb,Alive,Fair,Acer rubrum,red maple,...,5011202,New York,40.574138,-74.092823,9.584633e+05,148463.8852,50.0,11202.0,5054617.0,5.038000e+09
641816,137011,323227,08/11/2015,52,0,OnCurb,Alive,Good,Acer rubrum,red maple,...,4109700,New York,40.770431,-73.777935,1.045759e+06,220043.4622,19.0,1097.0,4135748.0,4.061040e+09

**Important**: Take note of the syntax here. We surround each condition with parentheses, and we use bitwise operators (`&`, `|`, `~`) instead of logical operators (`and`, `or`, `not`).

Use logical operators (and, or, not) → for plain Booleans in conditions/flow control.

Use bitwise operators (&, |, ^, ~, etc.) → for binary math, masks, or array-wise logic.

With pandas/NumPy, you must use &, |, ~ for combining conditions, not and/or:

*Tip: Boolean masks can be used with `loc[]` and `iloc[]`.*

In [28]:
tree2015[(tree2015['tree_dbh'] > 40) & (tree2015.spc_common == 'red maple')].iloc[0:10]

,tree_id,block_id,created_at,tree_dbh,stump_diam,curb_loc,status,health,spc_latin,spc_common,...,boro_ct,state,latitude,longitude,x_sp,y_sp,council district,census tract,bin,bbl
20379,215697,415159,09/11/2015,51,0,OffsetFromCurb,Alive,Good,Acer rubrum,red maple,...,5013204,New York,40.563976,-74.127037,9.489533e+05,144773.8257,50.0,13204.0,NaN,NaN
37509,245977,334366,09/22/2015,41,0,OnCurb,Alive,Good,Acer rubrum,red maple,...,4056800,New York,40.719414,-73.731788,1.058598e+06,201492.3129,27.0,568.0,4231341.0,4.108110e+09
56702,225461,514975,09/15/2015,41,0,OnCurb,Alive,Good,Acer rubrum,red maple,...,2042800,New York,40.893187,-73.844652,1.027200e+06,264728.0536,12.0,428.0,2069001.0,2.050160e+09
94481,277901,511000,10/02/2015,41,0,OnCurb,Alive,Good,Acer rubrum,red maple,...,2030000,New York,40.853706,-73.828386,1.031725e+06,250351.9682,13.0,300.0,2047760.0,2.042490e+09
231191,430014,402102,11/05/2015,43,0,OnCurb,Alive,Good,Acer rubrum,red maple,...,5002100,New York,40.625125,-74.083394,9.611006e+05,167037.1837,49.0,21.0,5014082.0,5.005420e+09
250198,456594,406164,11/14/2015,42,0,OnCurb,Alive,Good,Acer rubrum,red maple,...,5011202,New York,40.575706,-74.096047,9.575685e+05,149036.2430,50.0,11202.0,5054231.0,5.037340e+09
262847,481551,402603,11/24/2015,50,0,OnCurb,Alive,Good,Acer rubrum,red maple,...,5021300,New York,40.629782,-74.137094,9.461964e+05,168752.5684,49.0,213.0,5024838.0,5.010490e+09
300944,498911,407837,12/06/2015,154,0,OnCurb,Alive,Good,Acer rubrum,red maple,...,5029103,New York,40.600109,-74.166549,9.380000e+05,157956.3377,50.0,29103.0,5035610.0,5.021100e+09
331153,550014,403735,03/09/2016,48,0,OffsetFromCurb,Alive,Good,Acer rubrum,red maple,...,5000900,New York,40.643690,-74.080369,9.619465e+05,173800.1351,49.0,9.0,5000324.0,5.000210e+09
331213,550016,403735,03/09/2016,64,0,OffsetFromCurb,Alive,Good,Acer rubrum,red maple,...,5000900,New York,40.643542,-74.080251,9.619791e+05,173746.2657,49.0,9.0,5131387.0,5.000200e+09

## Calculating summary statistics
We can extract some interesting insights from the `tree2015` data by calculating summary statistics.

#### What was the mass of the average tee_dbh

In [68]:
tree2015['tree_dbh'].mean()

np.float64(11.27978701000895)

**Important**: The mean isn't always the best measure of central tendency. If there are outliers in the distribution, the mean will be skewed. Here, the mean is being pulled higher by some very heavy meteorites &ndash; the distribution is [right-skewed](https://www.analyticsvidhya.com/blog/2020/07/what-is-skewness-statistics/).

Taking a look at some quantiles at the extremes of the distribution shows that the mean is between the 95th and 99th percentile of the distribution, so it isn't a good measure of central tendency here:

In [29]:
tree2015['tree_dbh'].quantile([0.01, 0.05, 0.5, 0.95, 0.99])

0.01     0.0
0.05     2.0
0.50     9.0
0.95    28.0
0.99    36.0
Name: tree_dbh, dtype: float64

A better measure in this case is the median (50th percentile), since it is robust to outliers:

In [70]:
tree2015['tree_dbh'].median()

np.float64(9.0)

#### What was the largest tree?

In [36]:
tree2015['tree_dbh'].max()

np.int64(450)

In [72]:
tree2015.loc[tree2015['tree_dbh'].idxmax()]

tree_id                                                      433258
block_id                                                     507833
created_at                                               11/05/2015
tree_dbh                                                        450
stump_diam                                                        0
curb_loc                                             OffsetFromCurb
status                                                         Dead
health                                                          NaN
spc_latin                                                       NaN
spc_common                                                      NaN
steward                                                         NaN
guards                                                          NaN
sidewalk                                                        NaN
user_type                                          TreesCount Staff
problems                                                        NaN
root_stone                                                       No
root_grate                                                       No
root_other                                                       No
trunk_wire                                                       No
trnk_light                                                       No
trnk_other                                                       No
brch_light                                                       No
brch_shoe                                                        No
brch_other                                                       No
address                                       1950 LAFAYETTE AVENUE
postcode                                                      10473
zip_city                                                      Bronx
community board                                                 209
borocode                                                          2
borough                                                       Bronx
cncldist                                                         18
st_assem                                                         87
st_senate                                                        32
nta                                                            BX09
nta_name            Soundview-Castle Hill-Clason Point-Harding Park
boro_ct                                                     2001600
state                                                      New York
latitude                                                  40.821953
longitude                                                -73.857671
x_sp                                                    1023642.915
y_sp                                                    238768.6665
council district                                               18.0
census tract                                                   16.0
bin                                                       2022207.0
bbl                                                    2036060001.0
Name: 228048, dtype: object

#### How many different types of tree species are in this dataset and what are they?

In [37]:
tree2015['spc_common'].nunique() # How many distinct values?

132

Some examples:

In [38]:
tree2015['spc_common'].unique() # What are the distinct values?

array(['red maple', 'pin oak', 'honeylocust', 'American linden',
       'London planetree', 'ginkgo', 'willow oak', 'sycamore maple',
       'Amur maple', nan, 'hedge maple', 'American elm', 'ash',
       'crab apple', 'silver maple', 'Turkish hazelnut', 'black cherry',
       'eastern redcedar', 'Norway maple', 'tulip-poplar', 'sawtooth oak',
       'swamp white oak', 'Sophora', 'Chinese fringetree',
       'southern magnolia', 'sweetgum', 'Callery pear', 'scarlet oak',
       'Atlantic white cedar', 'black oak', 'Japanese zelkova',
       'white oak', 'Ohio buckeye', 'northern red oak', 'silver linden',
       'pignut hickory', 'Kentucky yellowwood', 'mulberry', 'Douglas-fir',
       'crepe myrtle', 'sassafras', 'cherry', 'spruce', 'Chinese elm',
       'horse chestnut', 'holly', 'littleleaf linden', 'white pine',
       'blackgum', 'Japanese tree lilac', 'hardy rubber tree',
       'green ash', 'English oak', 'white ash', 'golden raintree',
       "Schumard's oak", 'Siberian elm', 'black walnut', 'weeping willow',
       'katsura tree', 'black locust', 'Persian ironwood',
       'Cornelian cherry', 'Chinese chestnut', 'southern red oak',
       'purple-leaf plum', 'crimson king maple', 'Kentucky coffeetree',
       'Japanese snowbell', 'sugar maple', 'arborvitae',
       'Oklahoma redbud', 'tree of heaven', 'Chinese tree lilac',
       'American hornbeam', 'eastern cottonwood', 'eastern hemlock',
       'silver birch', 'Atlas cedar', 'empress tree', 'hawthorn',
       "'Schubert' chokecherry", 'catalpa', 'river birch', 'boxelder',
       'European beech', 'Norway spruce', 'Himalayan cedar',
       'Amur cork tree', 'Japanese maple', 'shingle oak', 'magnolia',
       'smoketree', 'paper birch', 'American beech',
       'American hophornbeam', 'American larch', 'pond cypress',
       'cockspur hawthorn', 'dawn redwood', 'common hackberry',
       'flowering dogwood', 'maple', 'kousa dogwood', 'eastern redbud',
       'bald cypress', 'cucumber magnolia', 'serviceberry',
       'Osage-orange', 'paperbark maple', 'red pine', 'Scots pine',
       'tartar maple', 'black maple', 'blue spruce', 'quaking aspen',
       'red horse chestnut', 'black pine', 'Shantung maple',
       'European alder', 'Amur maackia', 'European hornbeam', 'bur oak',
       'bigtooth aspen', 'trident maple', 'Virginia pine',
       'two-winged silverbell', 'pagoda dogwood', 'Japanese hornbeam',
       'pine', 'false cypress', 'pitch pine', 'mimosa'], dtype=object)

#### Get some summary statistics on the data itself
We can get common summary statistics for all columns at once. By default, this will only be numeric columns, but here, we will summarize everything together:

In [39]:
tree2015['tree_dbh'].describe(include='all')

count    683788.000000
mean         11.279787
std           8.723042
min           0.000000
25%           4.000000
50%           9.000000
75%          16.000000
max         450.000000
Name: tree_dbh, dtype: float64

#### Check out the documentation for more descriptive statistics:

- [Series](https://pandas.pydata.org/docs/reference/series.html#computations-descriptive-stats)
- [DataFrame](https://pandas.pydata.org/docs/reference/frame.html#computations-descriptive-stats)

### [Exercise 1.3](./wk5.ipynb#Exercise-1.3)

##### Using the data in the 2005 NYC tree data, calculate summary statistics for tree_dbh column.

### [Exercise 1.4](./wk5.ipynb#Exercise-1.4)

##### Find out how many tree species and what they are in the 2005 tree dataset