# Section 2: Data Wrangling

To prepare our data for analysis, we need to perform data wrangling. In this section, we will learn how to clean and reformat data (e.g., renaming columns and fixing data type mismatches), restructure/reshape it, and enrich it (e.g., discretizing columns, calculating aggregations, and combining data sources).

## Data cleaning

In this section, we will take a look at creating, renaming, and dropping columns; type conversion; and sorting &ndash; all of which make our analysis easier. We will be working with the 2019 Yellow Taxi Trip Data provided by NYC Open Data.

In [1]:
import pandas as pd

In [15]:
tree2005 = pd.read_csv('data/2005_Street_Tree_Census.csv')

C:\Users\Wenge\AppData\Local\Temp\ipykernel_28760\4084950916.py:1: DtypeWarning: Columns (37) have mixed types. Specify dtype option on import or set low_memory=False.
  tree2005 = pd.read_csv('data/2005_Street_Tree_Census.csv')

In [17]:
tree2005.iloc[:,[37]]

        boroname
0       Brooklyn
1       Brooklyn
2       Brooklyn
3       Brooklyn
4       Brooklyn
...          ...
592367         5
592368         5
592369         5
592370         5
592371         5

[592372 rows x 1 columns]

### Dropping columns
Let's start by dropping some columns which we won't be using.

In [47]:
tree2005.columns

Index(['OBJECTID', 'cen_year', 'tree_dbh', 'address', 'tree_loc', 'pit_type',
       'soil_lvl', 'status', 'spc_latin', 'spc_common', 'vert_other',
       'vert_pgrd', 'vert_tgrd', 'vert_wall', 'horz_blck', 'horz_grate',
       'horz_plant', 'horz_other', 'sidw_crack', 'sidw_raise', 'wire_htap',
       'wire_prime', 'wire_2nd', 'wire_other', 'inf_canopy', 'inf_guard',
       'inf_wires', 'inf_paving', 'inf_outlet', 'inf_shoes', 'inf_lights',
       'inf_other', 'trunk_dmg', 'zipcode', 'zip_city', 'cb_num', 'borocode',
       'boroname', 'cncldist', 'st_assem', 'st_senate', 'nta', 'nta_name',
       'boro_ct', 'state', 'latitude', 'longitude', 'x_sp', 'y_sp',
       'objectid_1', 'census tract', 'bin', 'bbl', 'Location 1'],
      dtype='object')

In [10]:
columns2drop = ['cen_year', 'address', 'tree_loc', 'pit_type',
       'soil_lvl', 'status', 'spc_latin',  'vert_other',
       'vert_pgrd', 'vert_tgrd', 'vert_wall', 'horz_blck', 'horz_grate',
       'horz_plant', 'horz_other', 'sidw_crack', 'sidw_raise', 'wire_htap',
       'wire_prime', 'wire_2nd', 'wire_other', 'inf_canopy', 'inf_guard',
       'inf_wires', 'inf_paving', 'inf_outlet', 'inf_shoes', 'inf_lights',
       'inf_other', 'trunk_dmg', 'zipcode', 'zip_city', 'cb_num', 
        'cncldist', 'st_assem', 'st_senate', 'nta', 'nta_name',
       'boro_ct', 'state', 'latitude', 'longitude', 'x_sp', 'y_sp',
       'objectid_1', 'census tract', 'bin', 'bbl', 'Location 1']
tree2005 = tree2005.drop(columns=columns2drop)

In [11]:
tree2005.columns

Index(['OBJECTID', 'tree_dbh', 'spc_common', 'borocode', 'boroname'], dtype='object')

In [51]:
tree2005

        OBJECTID  tree_dbh            spc_common  borocode  boroname
0         592373         6         PEAR, CALLERY         3  Brooklyn
1         592374         6      LONDON PLANETREE         3  Brooklyn
2         592375        13  MAPLE, NORWAY-CR KNG         3  Brooklyn
3         592376        13      LONDON PLANETREE         3  Brooklyn
4         592377        15      LONDON PLANETREE         3  Brooklyn
...          ...       ...                   ...       ...       ...
592367   1184740         9      LONDON PLANETREE         5         5
592368   1184741         7         MAPLE, SILVER         5         5
592369   1184742         5  MAPLE, NORWAY-CR KNG         5         5
592370   1184743         9  MAPLE, NORWAY-CR KNG         5         5
592371   1184744         2  MAPLE, NORWAY-CR KNG         5         5

[592372 rows x 5 columns]

### Tips: 
- Another way to do this is to select the columns we want to keep: `tree2015.loc[:,~columns2drop]`
- If you know the column names that you want, you can just read the data for specific columns

In [28]:
tree2005  = pd.read_csv('data/2005_Street_Tree_Census.csv', usecols=['OBJECTID', 'tree_dbh', 'spc_common', 'borocode', 'boroname'])
tree2005

C:\Users\Wenge\AppData\Local\Temp\ipykernel_28760\3626372425.py:1: DtypeWarning: Columns (37) have mixed types. Specify dtype option on import or set low_memory=False.
  tree2005  = pd.read_csv('data/2005_Street_Tree_Census.csv', usecols=['OBJECTID', 'tree_dbh', 'spc_common', 'borocode', 'boroname'])

        OBJECTID  tree_dbh            spc_common  borocode  boroname
0         592373         6         PEAR, CALLERY         3  Brooklyn
1         592374         6      LONDON PLANETREE         3  Brooklyn
2         592375        13  MAPLE, NORWAY-CR KNG         3  Brooklyn
3         592376        13      LONDON PLANETREE         3  Brooklyn
4         592377        15      LONDON PLANETREE         3  Brooklyn
...          ...       ...                   ...       ...       ...
592367   1184740         9      LONDON PLANETREE         5         5
592368   1184741         7         MAPLE, SILVER         5         5
592369   1184742         5  MAPLE, NORWAY-CR KNG         5         5
592370   1184743         9  MAPLE, NORWAY-CR KNG         5         5
592371   1184744         2  MAPLE, NORWAY-CR KNG         5         5

[592372 rows x 5 columns]

### Renaming columns

Next, let's rename boroname to borough to be consistent with the 2015 data. You could work the other way around, rename 2015 'borough` into 'boroname`:

In [29]:
tree2005 = tree2005.rename(columns={'boroname':'borough'})
tree2005.columns

Index(['OBJECTID', 'tree_dbh', 'spc_common', 'borocode', 'borough'], dtype='object')

In [92]:
tree2005

        OBJECTID  tree_dbh            spc_common  borocode   borough
0         592373         6         PEAR, CALLERY         3  Brooklyn
1         592374         6      LONDON PLANETREE         3  Brooklyn
2         592375        13  MAPLE, NORWAY-CR KNG         3  Brooklyn
3         592376        13      LONDON PLANETREE         3  Brooklyn
4         592377        15      LONDON PLANETREE         3  Brooklyn
...          ...       ...                   ...       ...       ...
592367   1184740         9      LONDON PLANETREE         5         5
592368   1184741         7         MAPLE, SILVER         5         5
592369   1184742         5  MAPLE, NORWAY-CR KNG         5         5
592370   1184743         9  MAPLE, NORWAY-CR KNG         5         5
592371   1184744         2  MAPLE, NORWAY-CR KNG         5         5

[592372 rows x 5 columns]

In [30]:
tree2005.loc[tree2005.borocode == 5,'borough'] = 'Staten Island'

In [110]:
tree2005

        OBJECTID  tree_dbh            spc_common  borocode        borough
0         592373         6         PEAR, CALLERY         3       Brooklyn
1         592374         6      LONDON PLANETREE         3       Brooklyn
2         592375        13  MAPLE, NORWAY-CR KNG         3       Brooklyn
3         592376        13      LONDON PLANETREE         3       Brooklyn
4         592377        15      LONDON PLANETREE         3       Brooklyn
...          ...       ...                   ...       ...            ...
592367   1184740         9      LONDON PLANETREE         5  Staten Island
592368   1184741         7         MAPLE, SILVER         5  Staten Island
592369   1184742         5  MAPLE, NORWAY-CR KNG         5  Staten Island
592370   1184743         9  MAPLE, NORWAY-CR KNG         5  Staten Island
592371   1184744         2  MAPLE, NORWAY-CR KNG         5  Staten Island

[592372 rows x 5 columns]

### [Exercise 2.1](./wk5.ipynb#Exercise-2.1)
Download and read 1995 NYC tree data from  [here](https://data.cityofnewyork.us/Environment/1995-Street-Tree-Census/kyad-zm4j/about_data)

Download 2005 NYC tree data from [here](https://data.cityofnewyork.us/Environment/2005-Street-Tree-Census/29bw-z7pj/about_data)

Download and read 2015 NYC tree data from [here](https://data.cityofnewyork.us/Environment/2015-Street-Tree-Census-Tree-Data/uvpi-gqnh/about_data).

Drop all the columns except for ['tree_id','tree_dbh', 'spc_common', 'borocode', 'borough'] columns. Sort the result by tree_id in descending order. Each dataset may have slightly different names for these columns, you need to check then first.

### Groupbying and Sorting by values
`groupby` is a very useful pandas function to do many things. 
We can use the `sort_values()` method to sort based on any number of columns:

In [20]:
# Find the most dominant species and tree counts
treecount2005 = tree2005.groupby('spc_common').size()
treecount2005_sorted = treecount2005.sort_values(ascending=False)
treecount2005_sorted[0:20]

spc_common
LONDON PLANETREE        89529
MAPLE, NORWAY           74721
PEAR, CALLERY           63593
HONEYLOCUST             52191
OAK, PIN                43895
LINDEN, LITTLE LEAF     27664
ASH, GREEN              20624
MAPLE, RED              20254
MAPLE, SILVER           18666
UNKNOWN                 18362
GINKGO                  16256
ZELKOVA, JAPANESE       14625
OAK, NORTHERN RED       11076
CHERRY, OTHER            9728
SWEETGUM                 8385
MAPLE, NORWAY-CR KNG     8134
LINDEN, AMERICAN         7229
JAPANESE PAGODA TREE     7067
LINDEN, SILVER           6013
ELM, AMERICAN            5462
dtype: int64

In [21]:
# Select big trees 
bigtree2005 = tree2005.loc[tree2005['tree_dbh'] > 40]
bigtree2005.shape

(4832, 5)

In [22]:
# Find the most dominant species and tree counts in big trees
bigtreecount2005 = bigtree2005.groupby('spc_common').size()
bigtreecount2005_sorted = bigtreecount2005.sort_values(ascending=False)
bigtreecount2005_sorted[0:10]

spc_common
LONDON PLANETREE       1657
MAPLE, SILVER           632
OAK, PIN                510
MAPLE, NORWAY           441
OAK, NORTHERN RED       239
MAPLE, RED              140
UNKNOWN                 122
LINDEN, LITTLE LEAF     106
PEAR, CALLERY            97
HONEYLOCUST              90
dtype: int64

### [Exercise 2.2](./wk5.ipynb#Exercise-2.2)

##### Find out top 10 dominant tree species for 2015, 2005 and 1995 NYC tree datasets

### [Exercise 2.3](./wk5.ipynb#Exercise-2.3)
##### Find the most dominant species and tree counts for tree dbh > 40 inches for 2015, 2005 and 1995 NYC tree datasets

## Working with the index

So far, we haven't really worked with the index because it's just been a row number; however, we can change the values we have in the index to access additional features of the pandas library.

### Setting and sorting the index

Currently, we have a RangeIndex, but we can switch to an index when calling `set_index()`:

In [31]:
tree2005

        OBJECTID  tree_dbh            spc_common  borocode        borough
0         592373         6         PEAR, CALLERY         3       Brooklyn
1         592374         6      LONDON PLANETREE         3       Brooklyn
2         592375        13  MAPLE, NORWAY-CR KNG         3       Brooklyn
3         592376        13      LONDON PLANETREE         3       Brooklyn
4         592377        15      LONDON PLANETREE         3       Brooklyn
...          ...       ...                   ...       ...            ...
592367   1184740         9      LONDON PLANETREE         5  Staten Island
592368   1184741         7         MAPLE, SILVER         5  Staten Island
592369   1184742         5  MAPLE, NORWAY-CR KNG         5  Staten Island
592370   1184743         9  MAPLE, NORWAY-CR KNG         5  Staten Island
592371   1184744         2  MAPLE, NORWAY-CR KNG         5  Staten Island

[592372 rows x 5 columns]

In [32]:
tree2005 = tree2005.set_index('borocode')

In [33]:
tree2005

          OBJECTID  tree_dbh            spc_common        borough
borocode
3           592373         6         PEAR, CALLERY       Brooklyn
3           592374         6      LONDON PLANETREE       Brooklyn
3           592375        13  MAPLE, NORWAY-CR KNG       Brooklyn
3           592376        13      LONDON PLANETREE       Brooklyn
3           592377        15      LONDON PLANETREE       Brooklyn
...            ...       ...                   ...            ...
5          1184740         9      LONDON PLANETREE  Staten Island
5          1184741         7         MAPLE, SILVER  Staten Island
5          1184742         5  MAPLE, NORWAY-CR KNG  Staten Island
5          1184743         9  MAPLE, NORWAY-CR KNG  Staten Island
5          1184744         2  MAPLE, NORWAY-CR KNG  Staten Island

[592372 rows x 4 columns]

Since we have a sample of the full dataset, let's sort the index to order borocode:

In [39]:
tree2005 = tree2005.sort_index()
tree2005

          OBJECTID  tree_dbh            spc_common        borough
borocode
1           592393         6         PEAR, CALLERY      Manhattan
1           592423         8   LINDEN, LITTLE LEAF      Manhattan
1           592422        10                GINKGO      Manhattan
1           592421         8         PEAR, CALLERY      Manhattan
1           592420        11                GINKGO      Manhattan
...            ...       ...                   ...            ...
5          1184714        13      LONDON PLANETREE  Staten Island
5          1184713         7            ASH, GREEN  Staten Island
5          1184726        12   LINDEN, LITTLE LEAF  Staten Island
5          1184744         2  MAPLE, NORWAY-CR KNG  Staten Island
5          1184725         5         PEAR, CALLERY  Staten Island

[592372 rows x 4 columns]

When not specifying a range, we use `loc[]`:

In [118]:
tree2005.loc[5]

          OBJECTID        borough            spc_common  tree_dbh
borocode
5          1184723  Staten Island         CHERRY, OTHER        10
5          1184729  Staten Island         CHERRY, OTHER        12
5          1184708  Staten Island  MAPLE, NORWAY-CR KNG         8
5          1184707  Staten Island         MAPLE, NORWAY         4
5          1184706  Staten Island         PEAR, CALLERY         5
...            ...            ...                   ...       ...
5          1184714  Staten Island      LONDON PLANETREE        13
5          1184713  Staten Island            ASH, GREEN         7
5          1184726  Staten Island   LINDEN, LITTLE LEAF        12
5          1184744  Staten Island  MAPLE, NORWAY-CR KNG         2
5          1184725  Staten Island         PEAR, CALLERY         5

[99701 rows x 4 columns]

### Resetting the index

Sometimes we want to reset our index to row numbers and restore the columns with the `reset_index()` method:

In [40]:
tree2005 = tree2005.reset_index()
tree2005.head()

   borocode  OBJECTID  tree_dbh           spc_common    borough
0         1    592393         6        PEAR, CALLERY  Manhattan
1         1    592423         8  LINDEN, LITTLE LEAF  Manhattan
2         1    592422        10               GINKGO  Manhattan
3         1    592421         8        PEAR, CALLERY  Manhattan
4         1    592420        11               GINKGO  Manhattan

### [Exercise 2.4](./wok5.ipynb#Exercise-2.4)

##### Find out the total number tree counts for each borough for 2015 NYC tree data

## Reshaping data
Sometimes the data format is not what we want, we need to reshape the data format using melt or pivoting. We will discuss this when we analyze real data in later sections.

## Time series
We will cover this in the future section when we deal with real data in the future modules.

[Pandas cheat sheet](https://github.com/pandas-dev/pandas/blob/main/doc/cheatsheet/Pandas_Cheat_Sheet.pdf)