In [4]:
import pandas as pd

data = {
    'City': ['New York', 'New York', 'Boston', 'Boston', 'Chicago', 'Chicago'],
    'Month': ['Jan', 'Feb', 'Jan', 'Feb', 'Jan', 'Feb'],
    'Sales': [250, 300, 200, 220, 180, 210]
}

df = pd.DataFrame(data)
df

       City Month  Sales
0  New York   Jan    250
1  New York   Feb    300
2    Boston   Jan    200
3    Boston   Feb    220
4   Chicago   Jan    180
5   Chicago   Feb    210

In [6]:
data = {
    'City': ['New York', 'New York', 'Boston', 'Boston', 'Chicago'],
    'Month': ['Jan', 'Feb', 'Jan', 'Feb', 'Jan'],
    'Sales': [250, 300, 200, 220, 180]
}

df = pd.DataFrame(data)
df

       City Month  Sales
0  New York   Jan    250
1  New York   Feb    300
2    Boston   Jan    200
3    Boston   Feb    220
4   Chicago   Jan    180

In [7]:
pd.pivot_table(df, values='Sales', index='City', columns='Month')

Month       Feb    Jan
City
Boston    220.0  200.0
Chicago     NaN  180.0
New York  300.0  250.0